#!/usr/bin/perl
$|=1;
while (<>) {
my $chan = "";
if (s/^(\d+\s+)//o) {
$chan = $1;
}
@X = split(" ",$_);
 
if ($X[0] =~ m/^https?\:\/\/.*(youtube|googlevideo).*(videoplayback|videogoodput).*/){
        @itag = m/[&?](itag=[0-9]*)/;
        @id = m/[&?]id\=([^\&\s]*)/;
        @mime = m/[&?](mime\=[^\&\s]*)/;
        @cpn = m/[&?]cpn\=([^\&\s]*)/;
        @range = m/[&?](range=[^\&\s]*)/;
    if ($X[1] =~ m/\.*(.*(youtube\.com\/.*))(embed|v)[=%&?\/](.*)/) {
            @id = $2;
        }
        print $chan, "OK store-id=http://youtube.uji.ganteng/@id&@itag&@mime&@range\n" ;

} elsif ($X[0] m/^https?\:\/\/.*youtube.*ptracking.*/){
	@video_id = m/[&?]video_id\=([^\&\s]*)/;
	@cpn = m/[&?]cpn\=([^\&\s]*)/;
	unless (-e "/tmp/@cpn"){
	open FILE, ">/tmp/@cpn";
	print FILE "@video_id";
	close FILE;
	}
	print $chan, "ERR";
 
} elsif ($X[0] =~ m/^https?\:\/\/.*youtube.*stream_204.*/){
	@docid = m/[&?]docid\=([^\&\s]*)/;
	@cpn = m/[&?]cpn\=([^\&\s]*)/;
	unless (-e "/tmp/@cpn"){
	open FILE, ">/tmp/@cpn";
	print FILE "@docid";
	close FILE;
	}
	print $chan, "ERR";
 
} elsif ($X[0] =~ m/^https?\:\/\/.*youtube.*player_204.*/){
	@v = m/[&?]v\=([^\&\s]*)/;
	@cpn = m/[&?]cpn\=([^\&\s]*)/;
	unless (-e "/tmp/@cpn"){
	open FILE, ">/tmp/@cpn";
	print FILE "@v";
	close FILE;
	}
	print $chan, "ERR";
 
} elsif ($X[0] =~ m/^https?\:\/\/.*((\.googlevideo\.com)).*$/){
	@itag = m/[&?](itag\=[0-9]*)/;
	@range = m/[&?](range\=[^\&\s]*)/;
	@cpn = m/[&?]cpn\=([^\&\s]*)/;
	@mime = m/[&?](mime\=[^\&\s]*)/;
	@id = m/[&?]id\=([^\&\s]*)/;
 
	if (defined(@cpn[0])){
		if (-e "/tmp/@cpn"){
		open FILE, "/tmp/@cpn";
		@id = <FILE>;
		close FILE;}
	}
	print $chan, "OK store-id=http://kangmus.video-srv.ganteng.com/id=@id&@itag&@range&@mime\n" ;

} elsif ($X[0] =~ m/^http?:\/\/.*\.steampowered\.com\/depot\/[0-9]+\/chunk\/([^\?]*)/){
        print $chan, "OK store-id=http://kangmus.ganteng.com/n";
 
} elsif ($X[0] =~ m/^https?\:\/\/(media|valve).*steampowered.*\/(client|depot)\/(.*)/) {
     	print $chan, "OK store-id=http://kangmus.ganteng.com/" . $2 . "/" . $3;

} elsif ($X[0] =~ m/^https?:\/\/.*lytogame\.com\/.*\/([a-zA-Z]+\/(.*))/) {
	print $chan, "OK store-id=http://kangmus.ganteng.com/" . $1;

} elsif ($X[0] =~ m/http.*\.(fbcdn|akamaihd)\.net\/h(profile|photos).*[\d\w].*\/([\w]\d+x\d+\/.*\.[\d\w]{3}).*/) {
	print $chan, "OK store-id=http://kangmus.ganteng.com/" . $2 . "/" . $3 ;

} elsif ($X[0] =~ m/^http(.*)static(.*)(akamaihd|fbcdn).net\/rsrc.php\/(.*\/.*\/(.*).(js|css|png|gif))(\?(.*)|$)/) {
	print $chan, "OK store-id=http://kangmus.ganteng.com/" . $5 . "." . $6 ;

} elsif ($X[0] =~ m/^https?\:\/\/.*utm.gif.*/) {
	print $chan, "OK store-id=http://kangmus.ganteng.com/__utm.gif";
 
} elsif ($X[0] =~ m/^https?\:\/\/.*\/speedtest\/(.*\.(jpg|txt)).*/) {
	print $chan, "OK store-id=http://kangmus.ganteng.com/" . $1;

} elsif ($X[0] =~ m/^https?:\/\/[a-zA-Z0-9]+\.[a-zA-Z0-9]+x\.[a-z]\.avast\.com\/[a-zA-Z0-9]+x\/(.*\.vpx)/) {
        print $chan, "OK store-id=http://kangmus.ganteng.com/" . $1 ;

} elsif ($X[0] =~ m/^https?:\/\/\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}\/(iavs.*)/) {
        print $chan, "OK store-id=http://kangmus.ganteng.com/" . $1 ;
 
} elsif ($X[0] =~ m/^https?\:\/\/.*\/(.*\..*(mp4|3gp|flv))\?.*/) {
	print $chan, "OK store-id=http://kangmus.ganteng.com/" . $1;

} elsif ($X[0] =~ m/^https?\:\/\/c2lo\.reverbnation\.com\/audio_player\/ec_stream_song\/(.*)\?.*/) {
	print $chan, "OK store-id=http://kangmus.ganteng.com/" . $1;
 
} elsif ($X[0] =~ m/^https?\:\/\/.*\.c\.android\.clients\.google\.com\/market\/GetBinary\/GetBinary\/(.*\/.*)\?.*/) {
	print $chan, "OK store-id=http://kangmus.ganteng.com/" . $1;

} elsif ($X[0] =~ m/^http:\/\/([a-z])[0-9]?(\.gstatic\.com.*|\.wikimapia\.org.*)/) {
	print $chan, "OK store-id=http://kangmus.ganteng.com/" . $2;

} elsif ($X[0] =~ m/^https?:\/\/.*(googleusercontent.com|blogspot.com)\/(.*)\/([a-z0-9]+)(-[a-z]-[a-z]-[a-z]+)?\/(.*\.(jpg|png))/){
	print $chan, "OK store-id=http://kangmus.ganteng.com/" . $5;

} elsif ($X[0] =~ m/^https?:\/\/([a-z0-9.]*)(\.doubleclick\.net|\.quantserve\.com|.exoclick\.com|interclick.\com|\.googlesyndication\.com|\.auditude\.com|.visiblemeasures\.com|yieldmanager|cpxinteractive)(.*)/){
	print $chan, "OK store-id=http://kangmus.ganteng.com/" . $3;

} elsif ($X[0] =~ m/^http\:\/\/.*\.4shared\.com\/download\/(.*)\/.*/) {
	print $chan, "OK store-id=http://kangmus.ganteng.com/" . $1;

} elsif ($X[0] =~ m/^http:\/\/(www\.ziddu\.com.*\.[^\/]{3,4})\/(.*?)/) {
	print $chan, "OK store-id=http://kangmus.ganteng.com/" . $1;

} elsif ($X[0] =~ m/^http:\/\/(.*?)\.yimg\.com\/(.*?)\.yimg\.com\/(.*?)\?(.*)/) {
	print $chan, "OK store-id=http://kangmus.ganteng.com/" . $3;

} elsif (($X[0] =~ m/filehippo/) && (m/^https?:\/\/(.*?)\.(.*?)\/(.*?)\/(.*)\.([a-z0-9]{3,4})(\?.*)?/)) {
	@y = ($1,$2,$4,$5); $y[0] =~ s/[a-z0-9]{2,5}/cdn./;
	print $chan, "OK store-id=http://puji.test.perl/" . $3;
	
} elsif ($u[1] =~ m/^http:\/\/.*dlink__[23]Fdownload_[23]F([\w\d-]+)_3Ftsid.*/) {
	$1 =~ s/_5F/_/g;
	print $chan, "OK store-id=http://kangmus.ganteng.com/" . $1;


} else {
        print $chan, "ERR\n" ;
}

	if ($X[0] =~ m/^https?\:\/\/.*/) {
	print "$out\n";

} else {
	print $X[0] . " " . "$out\n";
}
}
