<?php
$viewinfo = $_GET['viewinfo'];

if($viewinfo == '1') {
phpinfo();
}else{
?>
<html>
<head>
<title>Test Page</title>
<meta http-equiv = "Content-Type" >
<head>
<body>
<h2>Welcome!</h2>
<p>this page was generated by APACHE</p>
<p>thank's your visit</p><p>PujiErmanto@Debian7 - 2016
<a href = 'test.php?viewinfo=1'>Click</a>
</body>
</html>
<?php
}
?>